[package]
name = "ethereum-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
alloy = { workspace = true, features = ["contract", "signer-local"] }
clap = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
subxt-core = { workspace = true }
