[package]
name = "ethereum-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
alloy = { workspace = true, features = ["contract", "signer-local"]}
log = { workspace = true }
subxt-core = "0.38.0"
