services: 
  omni-bridge:
    image: bridge:latest
    environment:
      - RUST_LOG=debug
    depends_on:
      - ethereum-node
      - heima-node
    volumes:
      - ./artifacts/:/artifacts
    ports:
      - "9090:9090"

  ethereum-node:
    image: ghcr.io/foundry-rs/foundry:v1.0.0
    command:
      - "anvil --host 0.0.0.0 --block-time 1"
    ports:
      - "8545:8545"

  ethereum-2-node:
    image: ghcr.io/foundry-rs/foundry:v1.0.0
    command:
      - "anvil --host 0.0.0.0 --block-time 1"
    ports:
      - "8546:8545"

  heima-node:
    image: litentry/litentry-parachain:latest
    ports:
      - "9944:9944"
    command: ["--dev", "--rpc-external"]

  bridge-contract-deployer:
    image: ghcr.io/foundry-rs/foundry:v1.0.0
    command: |
      - "forge create --root /app --no-cache Bridge --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-node:8545 --constructor-args 0 [] 0 0 0 && forge create --root /app ERC20Handler --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-node:8545 --constructor-args 0x5FbDB2315678afecb367f032d93F642f64180aa3 && forge create --root /app GenericHandler --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-node:8545 --constructor-args 0x5FbDB2315678afecb367f032d93F642f64180aa3 && forge create --root /app ERC721Handler --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-node:8545 --constructor-args 0x5FbDB2315678afecb367f032d93F642f64180aa3"
    volumes:
      - ./ethereum/chainbridge-contracts:/app
    depends_on:
      - ethereum-node

  bridge-contract-2-deployer:
    image: ghcr.io/foundry-rs/foundry:v1.0.0
    command: |
      - "forge create --root /app --no-cache Bridge --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-2-node:8545 --constructor-args 0 [] 0 0 0 && forge create --root /app ERC20Handler --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-2-node:8545 --constructor-args 0x5FbDB2315678afecb367f032d93F642f64180aa3 && forge create --root /app GenericHandler --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-2-node:8545 --constructor-args 0x5FbDB2315678afecb367f032d93F642f64180aa3 && forge create --root /app ERC721Handler --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-2-node:8545 --constructor-args 0x5FbDB2315678afecb367f032d93F642f64180aa3"
    volumes:
      - ./ethereum/chainbridge-contracts:/app
    depends_on:
      - ethereum-2-node

  lit-erc20-contract-deployer:
    image: ghcr.io/foundry-rs/foundry:v1.0.0
    command:
      - "forge create --root /app ERC20.sol:LITToken --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-node:8545"
    volumes:
      - ./artifacts/ethereum:/app
    depends_on:
      bridge-contract-deployer:
        condition: service_completed_successfully

  lit-erc20-2-contract-deployer:
    image: ghcr.io/foundry-rs/foundry:v1.0.0
    command:
      - "forge create --root /app ERC20.sol:LITToken --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-2-node:8545"
    volumes:
      - ./artifacts/ethereum:/app
    depends_on:
      bridge-contract-2-deployer:
        condition: service_completed_successfully

  hei-erc20-contract-deployer:
    image: ghcr.io/foundry-rs/foundry:v1.0.0
    command:
      - "forge create --root /app --hardhat contracts/heima/HEI.sol:HEI --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-node:8545 --constructor-args 0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9 Heima HEI 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    volumes:
      - ./artifacts/ethereum/HEI-token:/app
    depends_on:
      lit-erc20-contract-deployer:
        condition: service_completed_successfully

  hei-erc20-2-contract-deployer:
    image: ghcr.io/foundry-rs/foundry:v1.0.0
    command:
      - "forge create --root /app --hardhat contracts/heima/HEI.sol:HEI --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --rpc-url http://ethereum-2-node:8545 --constructor-args 0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9 Heima HEI 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    volumes:
      - ./artifacts/ethereum/HEI-token:/app
    depends_on:
      lit-erc20-2-contract-deployer:
        condition: service_completed_successfully

  api:
    image: web3labs/epirus-free-api:latest
    environment:
      - NODE_ENDPOINT=http://ethereum-node:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - REINDEX_ENDPOINT=http://ingestion/reindex/
      - MONGO_DB_NAME=epirus
      - MONGO_CREATE_INDICES=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mongodb

  mongodb:
    image: mongo:5.0.8
    environment:
      - COMPOSE_HTTP_TIMEOUT=900
      - DOCKER_CLIENT_TIMEOUT=900
    entrypoint: mongod --bind_ip "0.0.0.0"

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis

  web:
    image: web3labs/epirus-free-web:latest
    environment:
      - API_URL=/api
      - WS_API_URL=ws://localhost:8090
      - DISPLAY_NETWORK_TAB=disabled
    depends_on:
      - api
    ports:
      - "3000:3000"

  ingestion:
    image: web3labs/epirus-free-ingestion:latest
    environment:
      - NODE_ENDPOINT=http://ethereum-node:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=epirus
      - LIST_OF_METRICS_TO_CALCULATE_PER_MINUTE=hourly,daily,monthly,yearly
    depends_on:
      - mongodb
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./local/nginx/5xx.html:/www/error_pages/5xx.html
    ports:
      - ${PORT:-80}:80
    depends_on:
      - api
      - web