services:
  ethereum-node:
    image: ghcr.io/foundry-rs/foundry
    command:
      - "anvil --host 0.0.0.0 --block-time 1"
    ports:
      - "8545:8545"

  ethereum-2-node:
    image: ghcr.io/foundry-rs/foundry
    command:
      - "anvil --host 0.0.0.0 --block-time 1"
    ports:
      - "8546:8545"

  heima-node:
    image: litentry/heima:latest
    ports:
      - "9944:9944"
    command: ["--dev", "--rpc-external"]