[package]
name = "ethereum-relayer"
version = "0.1.0"
edition.workspace = true

[dependencies]
bridge-core = { workspace = true }
async-trait = { workspace = true }
alloy = { workspace = true, features = ["contract", "signer-local"]}
log = { workspace = true }
serde = { workspace = true }
