[package]
name = "bridge-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {  workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.127"
scale-encode = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
ethereum-listener = { path = "../ethereum/listener" }
ethereum-relayer = { path = "../ethereum/relayer" }
bridge-core = { path = "../bridge-core" }
substrate-listener = { path = "../substrate/listener" }
substrate-relayer = { path = "../substrate/relayer" }
hex = "0.4.3"