[package]
name = "bridge-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {  workspace = true, features = ["macros", "rt-multi-thread"] }
env_logger = { workspace = true }
log = { workspace = true }
ethereum-listener = { path = "../ethereum/listener" }
ethereum-relayer = { path = "../ethereum/relayer" }
substrate-listener = { path = "../substrate/listener" }
substrate-relayer = { path = "../substrate/relayer" }
hex = "0.4.3"
serde_json = { workspace = true }
serde = { version = "1.0.217", features = ["derive"] }
bridge-core = { path = "../bridge-core" }