[package]
name = "substrate-relayer"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
bridge-core = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
subxt = { workspace = true }
subxt-signer = { workspace = true }
