name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The commit SHA or tag for code checkout
        default: ""
        required: false
      docker_tag:
        description: docker tag of the built image
        default: "latest"
        required: true

env:
  REF_VERSION: ${{ github.event.inputs.ref || github.ref_name }}
  DOCKER_TAG: ${{ github.event.inputs.docker_tag }}

jobs:
  build-release:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Checkout codes on ${{ env.REF_VERSION }}
        uses: actions/checkout@v4
        with:
          ref: ${{ env.REF_VERSION }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Write enclave signing key
        run: |
          echo "${{ secrets.PROD_ENCLAVE_SIGNING_KEY }}" > enclave-key.pem

      - name: Write operational auth key
        run: |
          echo -n "${{ secrets.AUTH_KEY_PUB }}" > auth_key_pub.bin

      - name: Build release image
        run: |
          docker build --secret id=signer,src=enclave-key.pem -f Dockerfile.gramine --tag litentry/omni-bridge:${{ env.DOCKER_TAG }} .
          docker images --all

      - name: Dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image
        run: |
          docker push litentry/omni-bridge:${{ env.DOCKER_TAG }}